# Generated by Django 4.1.2 on 2022-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(default="india", max_length=100),
            preserve_default=False,
        ),
    ]
