# Generated by Django 4.1.2 on 2022-10-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_tag_book_description_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
